- hosts: master:slaves:database
  sudo: yes
  remote_user: dbnet
  tasks:
- name: restart server
  command: /sbin/reboot
  async: 0
  poll: 0
  ignore_errors: true
- name: wait for the server to restart
  local_action: wait_for host={{ inventory_hostname }}
  port=22
  delay=1
  timeout=300
  state=started
