- hosts: databasetest2
  sudo: yes
  remote_user: dbnet
  tasks:

  - name: Pulling newest docker image
    register: imagepulled
    command: docker pull ubuntu

  - name: Running image
    when: imagepulled|success
    register: running
    command: docker run --name="dummy2" --hostname="dummy2" -d ubuntu tail -f /dev/null

