- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:
  - name: Creating resource folder
    register: folderCreated
    file: path=/home/dbnet/resources state=directory owner=dbnet group=dbnet mode=0774 recurse=yes

  - name: Copying the resources to all hosts
    when: folderCreated|success
    register: resourcesCopied
    copy: src=/media/usb1/masterthesis/config-files/resources dest=/home/dbnet owner=dbnet group=dbnet mode=0664

  - name: Pulling newest docker image
    when: configcopied|success
    register: imagepulled
    shell: docker pull carnuel/hadoop

  - name: Running image
    when: imagepulled|success
    register: running
    shell: docker run -itd -v /home/dbnet/resources:/mnt --net="host" carnuel/hadoop
