- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
    logDest: /tmp/zips
    logSrc: /usr/local/hadoop/logs
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: zip log folder
    shell: zip logs.zip *
    args:
      chdir: "{{ logSrc }}"

  - name: fetch log files
    fetch: src={{ logSrc }}/logs.zip dest={{ logDest }}/logs/logs.zip flat=yes
