- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
    logDest: /tmp/zips
    logSrc: /usr/local/hadoop/logs
  sudo: yes
  remote_user: dbnet
  tasks:

  - name: Creating logs folder
    file: path={{ logDest }} state=directory owner=dbnet group=dbnet mode=0774 recurse=yes

  - name: Copy hadoop logs
    shell: cp -r {{ logSrc }}/*.log {{ logDest }}

  - name: zip log folder
    shell: zip logs.zip *
    args:
      chdir: "{{ logDest }}"

  - name: fetch log files
    fetch: src={{ logDest }}/logs.zip dest={{ logDest }}/logs/{{ ansible_hostname }}_logs.zip flat=yes
