- hosts: test
  sudo: yes
  remote_user: dbnet
  tasks:
  - name: Creating resource folder
    register: foldercreated
    file: path=/home/dbnet/resources state=directory owner=dbnet group=dbnet mode=0774 recurse=yes

  - name: Copying the cluster config to all hosts
    when: foldercreated|success
    register: configcopied
    copy: src=/media/usb1/masterthesis/config-files/resources dest=/home/dbnet owner=dbnet group=dbnet mode=0664

  - name: Pulling newest docker image
    when: configcopied|success
    register: imagepulled
    command: docker pull carnuel/hadoop-cluster:v2

  - name: Running image
    when: imagepulled|success
    register: running
    command: docker run -d -v /home/dbnet/resources:/mnt --net="host" carnuel/hadoop-cluster:v2
