- hosts: test
  sudo: yes
  remote_user: dbnet
  tasks:
  - name: Creating resource folder
    register: foldercreated
    file: path=/home/dbnet/resources state=directory owner=dbnet group=dbnet mode=0774 recurse=yes

  - name: Copying the cluster config to all hosts
    when: foldercreated|success
    register: configcopied
    copy: src=/media/usb1/masterthesis/config-files/resources dest=/home/dbnet owner=dbnet group=dbnet mode=0664

