- hosts: swarm-nodes
  sudo: yes
  remote_user: dbnet
  tasks:
  - name: Join cluster
    shell: docker run -d swarm join --addr={{ ansible_eth0.ipv4.address }}:2375 consul://136.199.51.110:8500

  - name: Pull newest image
    shell: docker pull carnuel/hadoop
