- hosts: database
  roles:
    - names
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: Run hadoop containers with specified names
    shell: docker run  --hostname={{ item }}  --name={{ item }} hello-world
    with_items: names

  - stat: path=container_Names.txt
    register: st

  - name: Delete old container_Names.txt
    when: st.stat.exists
    shell: rm container_Names.txt


  - name: Save long docker-name of Hadoop Containers to file
    shell: echo -n $(docker inspect --format={{'{{'}}.Node.Name{{'}}'}} {{item}}) >> container_Names.txt ; echo -n '%2Fsystem.slice%2Fdocker-' ; echo $(docker inspect --format={{'{{'}}.Id{{'}}'}} {{item}}) >> container_Names.txt
    with_items: names

 
