---
- hosts: swarm-manager:swarm-nodes
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:
  - name: Clear containers
    shell: clearContainers

- include: start_consul_on_manager.yml

- include: daemon_config_on_nodes.yml

- include: hadoop_resources_on_nodes.yml

- hosts: swarm-nodes
  sudo: yes
  gather_facts: yes
  remote_user: dbnet
  tasks:
  - name: Join cluster
    shell: docker run -d swarm join --addr={{ ansible_eth0.ipv4.address }}:2375 consul://136.199.51.110:8500

- hosts: swarm-manager
  sudo: yes
  gather_facts: yes
  remote_user: dbnet
  tasks:
  - name: Run manager
    shell: docker run -d -p 2375:2375 swarm manage consul://136.199.51.110:8500

  - name: Create overlay network
    shell: docker -H 0.0.0.0:2375 network create --driver overlay hadoop-cluster
 
  - name: Run hadoop container with name master
    shell: docker -H 0.0.0.0:2375  run -itd -v /home/dbnet/swarm_resources:/mnt --net="hadoop-cluster" --hostname="master" --name="master" carnuel/hadoop -d

  - name: Run hadoop container with name slave01
    shell: docker -H 0.0.0.0:2375  run -itd -v /home/dbnet/swarm_resources:/mnt --net="hadoop-cluster" --hostname="slave01" --name="slave01" carnuel/hadoop -d

  - name: Run hadoop container with name slave02
    shell: docker -H 0.0.0.0:2375  run -itd -v /home/dbnet/swarm_resources:/mnt --net="hadoop-cluster" --hostname="slave02" --name="slave02" carnuel/hadoop -d
