- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
  sudo: yes
  gather_facts: yes
  remote_user: dbnet
  tasks:

  - name: Removing resources
    shell: rm -rf /home/dbnet/swarm_resources

  - name: Remove daemon-settings.conf
    shell: rm /home/dbnet/daemon-settings.conf

- include: ../basics/reset_daemons.yml
#delete volume
- include: ../hosts/reboot.yml
