- hosts: cluster
  sudo: yes
  remote_user: dbnet
  tasks:

  - name: delete private folders (.<filename>)
    shell: rm -rf .cache && rm -rf .ansible && rm -rf .docker && rm -rf .oracle_jre_usage && rm -rf .sudo_as_admin_successful && rm -rf .viminfo && rm -rf .bash_history
