---
- hosts: "{{ hosts }}"
  vars:
    hosts: nodes:manager
    zip: /tmp/zips/
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: Check if zips folder exists
    stat: path={{ zip }}
    register: folder

  - name: Remove zip folder
    when: folder.stat.exists
    shell: rm -rf {{ zip }}

- hosts: 127.0.0.1
  vars:
     zip: /tmp/zips/
     namesDest: /tmp/container_names
  gather_facts: no
  connection: local
  tasks:

  - name: Check if zips folder exists
    stat: path={{ zip }}
    register: folder

  - name: Remove zip folder
    when: folder.stat.exists
    shell: rm -rf {{ zip }}

  - name: Check if names folder exists
    stat: path={{ namesDest }}
    register: folder

  - name: Remove names folder
    when: folder.stat.exists
    shell: rm -rf {{ namesDest }}

