- hosts: cluster
  sudo: yes
  remote_user: dbnet
  tasks:

  - name: delete private folders (.<filename>)
    shell: rm -rf .cache .ansible .docker .oracle_jre_usage .sudo_as_admin_successful .viminfo .bash_history
