- hosts: cluster
  sudo: yes
  remote_user: dbnet
  tasks:
  - name: restart machine
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }}
                  state=started
    sudo: false
