- hosts: cluster
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: Remove DOCKER_TLS_VERIFY from /etc/environment
    shell: sed -i "/^DOCKER_TLS_VERIFY=/d" /etc/environment
  - name: Add DOCKER_TLS_VERIFY to /etc/environment 
    shell: sed -i '$ a\DOCKER_TLS_VERIFY=1' /etc/environment
