- hosts: cluster
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: Remove 8.8.8.8
    shell: sed -i "/^nameserver 8.8.8.8" /etc/resolv.conf

  - name: Add 8.8.8.8
    shell: sed -i "$ a\nameserver 8.8.8.8" /etc/resolv.conf
