- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
  sudo: yes
  gather_facts: yes
  remote_user: dbnet
  tasks:

  - name: Creating resource folder
    register: folderCreated
    file: path=/home/dbnet/resources state=directory owner=dbnet group=dbnet mode=0774 recurse=yes

  - name: Copying the resources to all hosts
    when: folderCreated|success
    register: resourcesCopied
    copy: src=/media/usb1/masterthesis/config-files/resources dest=/home/dbnet owner=dbnet group=dbnet mode=0664

#  - name: Running hadoop
#    shell: docker run -itd -v /home/dbnet/resources:/mnt --net="host" --name="{{ ansible_hostname }}" carnuel/hadoop -d
