---
- include: ../basics/clear_containers.yml hosts=nodes:manager
- include: ../database/database.yml hosts=manager
- include: ../database/cadvisor.yml hosts=manager:nodes

- include: copy_resources.yml hosts=nodes
- include: run_container.yml hosts=nodes
