---
- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
    logDest: /tmp/zips
    logSrc: /usr/local/hadoop/logs
  roles:
    - metrics
  sudo: yes
  gather_facts: yes
  remote_user: dbnet
  tasks:

  - name: Creating logs folder
    file: path={{ logDest }} state=directory owner=dbnet group=dbnet mode=0774 recurse=yes

  - name: Copy hadoop logs
    shell: docker cp {{ ansible_hostname }}:{{ logSrc }} {{ logDest }}

  - name: delete security.auth
    shell: rm Sec*
    args:
      chdir: "{{ logDest }}/logs"

  - name: zip log files
    shell: zip logs.zip *
    args:
      chdir: "{{ logDest }}/logs"

  - name: fetch log files
    fetch: src={{ logDest }}/logs/logs.zip dest={{ logDest }}/logs/{{ ansible_hostname }}.zip flat=yes
