- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: Removing resources
    shell: rm -rf /home/dbnet/resources

- include: ../basics/clear_containers.yml
#- include: ../basics/clear_images.yml
- include: ../basics/clear_volumes.yml
- include: ../hosts/reboot.yml
