- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: Copying the hdfs-site.xml to all hosts
    when: unpacked|success
    copy: src=/media/usb1/masterthesis/config-files/no_docker_resources/hdfs-site.xml dest=/usr/local/hadoop/etc/hadoop/hdfs-site.xml owner=dbnet group=dbnet mode=0664

  - name: Copying the core-site.xml to all hosts
    when: unpacked|success
    copy: src=/media/usb1/masterthesis/config-files/no_docker_resources/core-site.xml dest=/usr/local/hadoop/etc/hadoop/core-site.xml owner=dbnet group=dbnet mode=0664

  - name: Copying the yarn-site.xml to all hosts
    when: unpacked|success
    copy: src=/media/usb1/masterthesis/config-files/no_docker_resources/yarn-site.xml dest=/usr/local/hadoop/etc/hadoop/yarn-site.xml owner=dbnet group=dbnet mode=0664

  - name: Copying the mapred-site.xml to all hosts
    when: unpacked|success
    copy: src=/media/usb1/masterthesis/config-files/no_docker_resources/mapred-site.xml dest=/usr/local/hadoop/etc/hadoop/mapred-site.xml owner=dbnet group=dbnet mode=0664

  - name: Copying the start_hadoop.sh
    copy: src=/media/usb1/masterthesis/config-files/no_docker_resources/start_hadoop.sh dest=/home/dbnet/start_hadoop.sh owner=dbnet group=dbnet mode=744

  - name: Copying the stop_hadoop.sh
    copy: src=/media/usb1/masterthesis/config-files/no_docker_resources/stop_hadoop.sh dest=/home/dbnet/stop_hadoop.sh owner=dbnet group=dbnet mode=744
