- hosts: "{{ hosts }}"
  vars:
    hosts: nodes
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: Check if log files exist
    stat: path=/usr/local/hadoop/logs
    register: logs

  - name: Copy log files to $HOME
    when: logs.stat.exists
    shell: cp -r /usr/local/hadoop/logs /home/dbnet/hadoop_logs
    register: logsCopied

  - name: Change ownership
    when: logsCopied|success
    file: path=/home/dbnet/hadoop_logs owner=dbnet group=dbnet recurse=yes
