- hosts: cluster
  sudo: yes
  gather_facts: no
  remote_user: dbnet
  tasks:

  - name: Get zip file
    register: downloaded
    get_url: url=https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip dest=0.5.2_linux_amd64.zip

  - name: unzip file
    when: downloaded|success
    register: unzipped
    unarchive: src=0.5.2_linux_amd64.zip dest=/usr/local/bin copy=no

  - name: delete zip file
    when: unzipped|success
    shell: rm 0.5.2_linux_amd64.zip
